# Configuration for Tomcat Server

server:
  port: 7777

# Configuration for Postgresql JDBC

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/go_work_db
    url: jdbc:postgresql://go-work-testing.c10eqacy8w6v.ap-south-1.rds.amazonaws.com/go_work_db
    username: postgres
    password: Vijay393
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Configuration for Postgresql Hibernate

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# Configuration for Amazon S3 Bucket

cloud:
  aws:
    region: ap-south-1
    keys:
      access-key: AKIAVPEYWJNBD6JS4P63
      secret-key: 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
    bucket-name: go-work-bucket

# Values for JwtService

application:
  security:
    secret-key: 1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM
    access_token:
      expiration: 43200000

# Configuration for Spring Email

  mail:
    host: smtp.gmail.com
    port: 587
    username: iamsuryavamsi@gmail.com
    password: "kqsc rbye uhzk zrjd"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
